config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  
  
  root to: 'toppages#index'
  
  get 'listspage', to: 'lists#index'
  
  resources :personaltabs, only: [:create, :destroy]
  resources :personallists, only: [:create, :destroy]
  resources :personalclassifications, only: [:create, :destroy]

  resources :groups, only: [:create, :destroy]

  resources :relationships, only: [:create, :destroy]

  resources :initialdisplays, only: [:create, :update, :destroy]
  
  resources :grouptabs, only: [:create, :destroy]
  resources :grouplists, only: [:create, :destroy]
  resources :groupclassifications, only: [:create, :destroy]  
  
  resources :id_unique_validates, only: [:create]  

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :sign_in_required
  
  def index
    @personaltab = current_user.personaltabs.build
    @personaltabs = current_user.personaltabs.order('created_at DESC')
    if @personaltabs.empty?
      @default_personaltab = current_user.personaltabs.build
      @default_personaltab.name = '初期リスト'
      @default_personaltab.save
    end

    active_personaltab_select 

    @personalclassification = @active_personaltab.personalclassifications.build
    @personalclassifications = @active_personaltab.personalclassifications.order('created_at ASC')
    if  @personalclassifications.empty?
      @default_personalclassification = @active_personaltab.personalclassifications.build
      @default_personalclassification.classification = '標準'
      @default_personalclassification.save
    end
    
    #@selected_class = @personalclassifications.find_by(classification: params[:selected_class])
    #unless @selected_class
    #  @selected_class = @personalclassifications.first
    #end
    
    @personallist = @active_personaltab.personallists.build
    @personallists = @active_personaltab.personallists.order('created_at ASC')    
    
    @group = current_user.groups.build
    
    @belonging_groups_counts = current_user.belonging_groups.count
    
    @relationship = current_user.relationships.build    
    
    counts(current_user)
    
    
    #------------------------------------------ここまでpersonal用
    
    #------------------------------------------ここからgroup用
    @active_grouptab = []
    @grouptab = []
    @grouptabs = []
    @grouplist = []
    @groupclassifications = []
    @selected_class_group = []
    @groupclassification = []
    @grouplists = []
    @groupmembers = []
    
    group_i = 0
    current_user.belonging_groups.each do |g|
      @groupmembers[group_i] = g.members.order('created_at DESC')
      @grouptab[group_i] = g.grouptabs.build
      @grouptabs[group_i] = g.grouptabs.order('created_at DESC')
      if @grouptabs[group_i].empty?
        @default_grouptab = g.grouptabs.build
        @default_grouptab.name = '初期リスト'
        @default_grouptab.save
        
      end





      temp = ('active_grouptab_id_' + group_i.to_s).to_sym 

      if (params[temp] && @grouptabs[group_i].find_by(id: params[temp]))
        @active_grouptab[group_i] = @grouptabs[group_i].find_by(id: params[temp])
      elsif @grouptabs[group_i].find_by(active: 'active')
        @active_grouptab[group_i] = @grouptabs[group_i].find_by(active: 'active')
      else
        @active_grouptab[group_i] = @grouptabs[group_i].first
      end
      if @grouptabs[group_i].find_by(active: 'active')
        @grouptabs[group_i].find_by(active: 'active').update(active: '')
      end
      @grouptabs[group_i].find_by(id: @active_grouptab[group_i].id).update(active: 'active')

      @groupclassification[group_i] = @active_grouptab[group_i].groupclassifications.build
      @groupclassifications[group_i] = @active_grouptab[group_i].groupclassifications.order('created_at ASC')
      if  @groupclassifications[group_i].empty?
        @default_groupclassification = @active_grouptab[group_i].groupclassifications.build
        @default_groupclassification.classification = '標準'
        @default_groupclassification.save
      end
      
      
      
      
      #@selected_class_group[group_i] = @groupclassifications[group_i].find_by(classification: params[:selected_class])
      #unless @selected_class_group[group_i]
      #  @selected_class_group[group_i] = @groupclassifications[group_i].first
      #end
      
      @grouplist[group_i] = @active_grouptab[group_i].grouplists.build
      @grouplists[group_i] = @active_grouptab[group_i].grouplists.order('created_at ASC')    
      
      # @group = current_user.groups.build
      # @relationship = current_user.relationships.build    
      # counts(current_user) 
      
      group_i = group_i + 1
      
    end
    
    unless (Initialdisplay.find_by(username: current_user.id) == nil)
      @initialdisplay_hidden_tag = Initialdisplay.find_by(username: current_user.id).initialdisplay_key
    else
      @initialdisplay_hidden_tag = 0
    end
    
  end

  def show
  end

  private

  def active_personaltab_select 
    if (params[:active_personaltab_id] && @personaltabs.find_by(id: params[:active_personaltab_id]))
      @active_personaltab = @personaltabs.find_by(id: params[:active_personaltab_id])
    elsif @personaltabs.find_by(active: 'active')
      @active_personaltab = @personaltabs.find_by(active: 'active')
    else
      @active_personaltab = @personaltabs.first
    end
    if @personaltabs.find_by(active: 'active')
      @personaltabs.find_by(active: 'active').update(active: '')
    end
    @personaltabs.find_by(id: @active_personaltab.id).update(active: 'active')
  end
   
end

app/views/lists/_groupshow.html.erb
<div id="target11">

<div id="list-outline">



<div id="fixedBox">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div>
        <h3 class="text-left">＜<%= current_user.belonging_groups.find_by(id: group_id).name %>＞</h3>

          <span class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">メンバー
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
                <% @groupmembers[groupindex].each do |g| %>
                  <li><a href="#"><%= g.setting_name %></a></li>
                <% end %>
            </ul>
          </span>
          
          <%= form_tag("/relationships", method: "post") do %>
            <div class="input-group col-sm-4 col-lg-3">
              <%= text_field_tag :add_member_id,'', class: 'form-control', placeholder: '追加メンバーのID' %>
              <span class="input-group-btn">
                <%= submit_tag "追加", class: 'btn btn-primary btn-block'  %>
                <%= hidden_field_tag :current_group, current_user.belonging_groups.find_by(id: group_id).id %>
              </span>
            </div>      
          <% end %>
          
      </div>
      <div class="navbar-header">
        <!-- 横幅が狭い時に出るハンバーガーボタン -->
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar<%= + (groupindex + 1) %>">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
  
        <!-- ホームへ戻るリンク。ブランドロゴなどを置く。 -->
        <a class="navbar-brand" href="#"><%= @active_grouptab[groupindex].name %></a>
      </div>
  
      <!-- メニュー項目 -->
      <div id="navbar<%= + (groupindex + 1) %>" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li>
            <%= form_for(@grouptab[groupindex]) do |f| %>
              <div class="input-group col-sm-4 col-lg-3">
                <%= f.text_field :name, class: 'form-control', placeholder: '新規リスト名' %>
                <span class="input-group-btn">
                  <%= f.submit '新規作成', class: 'btn btn-primary btn-block' %>
                  <%= hidden_field_tag :current_group, current_user.belonging_groups.find_by(id: group_id).id %>
                  <%= hidden_field_tag :createtab_groupindex, groupindex %>
                </span>
              </div>
            <% end %>
          </li>
          <% @grouptabs[groupindex].each do |grouptab| %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= grouptab.name %>
              <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <% temp = ('active_grouptab_id_' + groupindex.to_s).to_sym %>
                <li><%= link_to grouptab.name + 'を開く', listspage_path(temp => grouptab.id), data: { no_turbolink: true } %></li>
                <% if grouptab.group.join_this_group(current_user) && grouptab.name != '初期リスト'  %>
                  <li><%= link_to grouptab.name + 'を削除する', grouptab, method: :delete, data: { confirm: "You sure?" } %></li>
                <% end %>
              </ul>
            </li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</div>



<div id="addinput">



</div>


<div id="cards">
  <div class="row-eq-height">
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="form-horizontal" role="form">
          <div class="panel panel-default">

            <div class="panel-body">
              <div class="col-sm-10 col-sm-offset-1">
                <h4><u>分類ラベル追加</u></h4>
                <%= form_for(@groupclassification[groupindex]) do |f| %>
                  <div class="input-group">
                    <%= f.text_field :classification, class: 'form-control' %>
                    <span class="input-group-btn">
                      <%= f.submit '追加', class: 'btn btn-primary btn-block' %>
                      <%= hidden_field_tag :current_group, current_user.belonging_groups.find_by(id: group_id).id %>
                    </span>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>

    
    <% @groupclassifications[groupindex].each do |gc| %>
      <div class="col-xs-12 col-sm-6 col-md-4 listcontent">
        <div class="panel panel-warning">
          <div class="panel-heading">
            <h3 class="panel-title" style="text-align: center">
              <%= link_to '', gc, method: :delete, class: 'glyphicon glyphicon-remove-circle'%>
              <%= gc.classification %>
              
              
              
              
              </h3>
          </div>
          <div class="panel-body"></div>
          <ul class="list-group sortable">
            <% @grouplists[groupindex].where(classification: gc.classification).each do |gl| %>
              <li class="list-group-item">
                <%= link_to '', gl, method: :delete, class: 'glyphicon glyphicon-remove-circle'%>
                <%= gl.content %>
                
                
              
              </li>
            <% end %>
          </ul>
          
            <%= form_for(@grouplist[groupindex]) do |f| %>
              <div class="input-group">
                <%= f.text_field :content, autofocus: true, class: 'form-control', placeholder: '項目' %>

                <%= hidden_field_tag :classificationEach, gc.classification %>
                <span class="input-group-btn">
                  <%= f.submit '追加', class: 'btn btn-primary btn-block' %>
                  <%= hidden_field_tag :current_group, current_user.belonging_groups.find_by(id: group_id).id %>
                </span>
              </div>
            <% end %>

        </div>
      </div>  
    <% end %>
  </div>
</div>

</div>


</div>

app/views/lists/_show.html.erb
<div id="list-outline">
  
<%= hidden_field_tag :initialdisplay_tag, @initialdisplay_hidden_tag %>


<div id="fixedBox">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <h3 class="text-left">＜個人用＞</h3>
      
      <div class="navbar-header">
        <!-- 横幅が狭い時に出るハンバーガーボタン -->
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar<%= + groupindex %>">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
  
        <!-- ホームへ戻るリンク。ブランドロゴなどを置く。 -->
          <a class="navbar-brand" href="#">＜<%= @active_personaltab.name %>＞</a>
      </div>
  
      <!-- メニュー項目 -->
      <div id="navbar<%= + groupindex %>" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li>
            <%= form_for(@personaltab) do |f| %>
              <div class="input-group col-sm-4 col-lg-3">
                <%= f.text_field :name, class: 'form-control', placeholder: '新規リスト名' %>
                <span class="input-group-btn">
                  <%= f.submit '新規作成', class: 'btn btn-primary btn-block' %>
                </span>
              </div>
            <% end %>
          </li>
          <% @personaltabs.each do |personaltab| %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= personaltab.name %>
              <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to personaltab.name + 'を開く', listspage_path(active_personaltab_id: personaltab.id), data: { no_turbolink: true } %></li>
                <% if current_user == personaltab.user && personaltab.name != '初期リスト'  %>
                  <li><%= link_to personaltab.name + 'を削除する', personaltab, method: :delete, data: { confirm: "You sure?" } %></li>
                <% end %>
              </ul>
            </li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</div>

<div id="cards">
  <div class="row-eq-height">
    <div class="content-add">
      <div class="col-sm-6">
        <div class="form-horizontal" role="form">
          <div class="panel panel-default">
            <div class="panel-heading">
            </div>
            <div class="panel-body">
              <div class="col-sm-10 col-sm-offset-1">
                <h4><u>分類ラベル追加</u></h4>
                <%= form_for(@personalclassification) do |f| %>
                  <div class="input-group">
                    <%= f.text_field :classification, class: 'form-control' %>
                    <span class="input-group-btn">
                      <%= f.submit '追加', class: 'btn btn-primary btn-block' %>
                    </span>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    
    <% @personalclassifications.each do |pc| %>
      <div class="col-xs-12 col-sm-6 col-md-4 listcontent">
        <div class="panel panel-warning">
          <div class="panel-heading">
            <h3 class="panel-title" style="text-align: center">
              <%= link_to '', pc, method: :delete, class: 'glyphicon glyphicon-remove-circle'%>
              <%= pc.classification %>
              </h3>
          </div>
          <div class="panel-body"></div>
          <ul class="list-group sortable">
            <% @personallists.where(classification: pc.classification).each do |pl| %>
              <li class="list-group-item">
                <%= link_to '', pl, method: :delete, class: 'glyphicon glyphicon-remove-circle'%>
                <%= pl.content %>
              </li>
            <% end %>
          </ul>
          
          
            <%= form_for(@personallist) do |f| %>
              <div class="input-group">
                <%= f.text_field :content, autofocus: true, class: 'form-control', placeholder: '項目' %>

                <%= hidden_field_tag :classificationEach, pc.classification %>
                <span class="input-group-btn">
                  <%= f.submit '追加', class: 'btn btn-primary btn-block' %>
                </span>
              </div>
            <% end %>

          
          


          
        </div>
      </div>  
    <% end %>
  </div>
</div>

</div>

app/views/lists/index.html.erb
<%= form_for(@group) do |f| %>
  <div class="input-group col-sm-4 col-lg-3">
    <%= f.text_field :name, class: 'form-control', placeholder: '新規グループ名' %>
    <span class="input-group-btn">
      <%= f.submit '新規作成', class: 'btn btn-primary btn-block' %>
      <%= hidden_field_tag :belonging_groups_counts, @belonging_groups_counts %>
    </span>
  </div>
<% end %>
<div>
  <p></p>
</div>

<div id="main-gallery">
  
  <div class="gallery-cell gallery-cell-0"><%= render 'lists/show', groupindex: 0 %></div>

  <% i=0 %>
  <% current_user.belonging_groups.each do |f| %>
    <div class="gallery-cell gallery-cell-<%= i+1 %>"><%= render 'lists/groupshow', groupindex: i, group_id: f.id %></div>
    <% i=i+1 %>
  <% end %>

</div>