config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  
  
  root to: 'toppages#index'
  
  get 'listspage', to: 'lists#index'
  
  resources :personaltabs, only: [:create, :destroy]
  resources :personallists, only: [:create, :destroy]
  resources :personalclassifications, only: [:create, :destroy]

  resources :groups, only: [:create, :destroy]

  resources :relationships, only: [:create, :destroy]

  resources :initialdisplays, only: [:create, :update, :destroy]
  
  resources :grouptabs, only: [:create, :destroy]
  resources :grouplists, only: [:create, :destroy]
  resources :groupclassifications, only: [:create, :destroy]  
  
  resources :id_unique_validates, only: [:create]  

end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <% if message_type == 'notice' %>
    <% message_type = 'success' %>
  <% elsif message_type == 'alert' %>
    <% message_type = 'danger' %>
  <% end %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Grouplist</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.setting_name %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'アカウント編集', edit_user_registration_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'アカウント作成', new_user_registration_path %></li>
            <li><%= link_to 'ログイン', new_user_session_path %></li>
          <% end %>
        </ul>
      </div>

    </div>
  </nav>
</header>

app/views/layouts/_temp.html.erb
<%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>

    <%= hidden_field_tag :initial_display, 'a' %>
    <%= f.submit 'Unfollow', class: 'btn btn-danger btn-block' %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Orderlist</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    
    
    <script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js"></script>
    
    <%= include_gon(:init => true) %>
    
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>